/**
 * Freeze @skastr0/groundwork-core/plugin-sdk into prism-plugin/lib as a single
 * .ts module so Prism's plugin-tree copy (TS-only) + bun-bundle path is
 * self-contained. No Groundwork CLI at runtime.
 */
import { mkdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(fileURLToPath(new URL("..", import.meta.url)));
const entry = path.join(repoRoot, "packages", "core", "src", "plugin-sdk.ts");
const outDir = path.join(repoRoot, "prism-plugin", "lib");
const outTs = path.join(outDir, "plugin-sdk.generated.ts");

await mkdir(outDir, { recursive: true });

const result = await Bun.build({
  entrypoints: [entry],
  target: "node",
  format: "esm",
  packages: "bundle",
  sourcemap: "none",
  // Write to memory so we can force a .ts suffix Prism will copy.
  write: false,
});

if (!result.success) {
  const diagnostics = result.logs.map((log) => log.message).join("\n");
  throw new Error(`Failed to bundle plugin SDK:\n${diagnostics}`);
}

const artifact = result.outputs[0];
if (!artifact) {
  throw new Error("Bun.build produced no outputs for plugin SDK");
}

const body = await artifact.text();
const header = `// Generated by scripts/bundle-plugin-sdk.ts — do not edit by hand.
// Self-contained Groundwork plugin SDK (hooks + tools). Regenerated by: bun run plugin:sdk
`;
await Bun.write(outTs, `${header}${body}`);

// Clean obsolete mjs/shim from earlier layout.
await Bun.write(path.join(outDir, ".gitkeep"), "");
try {
  const { unlink } = await import("node:fs/promises");
  await unlink(path.join(outDir, "plugin-sdk.mjs")).catch(() => undefined);
  await unlink(path.join(outDir, "plugin-sdk.ts")).catch(() => undefined);
} catch {
  // ignore
}

console.log(`Bundled plugin SDK → ${outTs} (${body.length} bytes)`);
